# docker-compose.yaml
version: '3.7'

services:
  web:
    image: street-backend
    container_name: street-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      S3_URL: ${S3_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      SECRET_KEY: ${SECRET_KEY}
      DB_URL: ${DB_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      RTSPTOWEB_URL: ${RTSPTOWEB_URL}
